In [105]:
import pandas as pd
import requests 
from bs4 import BeautifulSoup
import numpy as np

In [106]:
headers= {'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage = requests.get("https://www.ambitionbox.com/list-of-companies?page=1",headers=headers).text

In [107]:
soup = BeautifulSoup(webpage, 'lxml')

In [108]:
soup.find_all('h1')[0].get_text(" ",strip=True)

'Top Companies in INDIA'

In [109]:
for i in soup.find_all('h2'):
    print(i.text.strip())

Companies in India
TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
HCLTech
ICICI Bank
Tech Mahindra
Genpact
TP
Jio
Axis Bank
Concentrix Corporation
Amazon
Reliance Retail
iEnergizer
LTIMindtree
IBM
Popular Collections by Industries
Popular Collections by Cities
Popular Collections by Roles

In [110]:
for i in soup.find_all('div',class_='rating_text'):
    print(i.text.strip())

3.3
3.7
3.6
3.7
3.6
3.8
3.5
3.4
3.9
3.4
3.6
3.9
4.4
3.6
3.6
3.9
3.9
4.6
3.6
3.9

In [111]:
company= soup.find_all('div',class_='companyCardWrapper')

In [112]:
len(company)

20

In [113]:
name = []
rating = []
review = []
salary = []
Jobs = []
About = []

for i in company:
    name.append(i.find('h2').text.strip())
    rating.append(i.find('div',class_='rating_text').text.strip())
    review.append(i.find_all('a',class_='companyCardWrapper__ActionWrapper')[0].text.strip())
    salary.append(i.find_all('a',class_='companyCardWrapper__ActionWrapper')[1].text.strip())
    Jobs.append(i.find_all('a',class_='companyCardWrapper__ActionWrapper')[3].text.strip())
    About.append(i.find('span',class_='companyCardWrapper__interLinking').text.strip())
    
d = {'Name':name, 'Rating':rating, 'Review':review, 'Salary':salary, 'Jobs':Jobs, 'About':About}

data = pd.DataFrame(d)

In [114]:
data

,Name,Rating,Review,Salary,Jobs,About
0,TCS,3.3,1.2L Reviews,10.2L Salaries,4.3k Jobs,IT Services & Consulting | Bengaluru +445 othe...
1,Accenture,3.7,74.2k Reviews,7.1L Salaries,34.9k Jobs,IT Services & Consulting | Bengaluru +259 othe...
2,Wipro,3.6,65.6k Reviews,4.9L Salaries,319 Jobs,IT Services & Consulting | Hyderabad +374 othe...
3,Cognizant,3.7,62k Reviews,6.1L Salaries,694 Jobs,IT Services & Consulting | Hyderabad +233 othe...
4,Capgemini,3.6,54k Reviews,4.9L Salaries,2.2k Jobs,IT Services & Consulting | Bengaluru +183 othe...
5,HDFC Bank,3.8,53k Reviews,1.5L Salaries,315 Jobs,Banking | Mumbai +1857 other locations
6,Infosys,3.5,49.3k Reviews,5.3L Salaries,2.5k Jobs,IT Services & Consulting | Bengaluru +246 othe...
7,HCLTech,3.4,46.4k Reviews,3.9L Salaries,305 Jobs,IT Services & Consulting | Chennai +231 other ...
8,ICICI Bank,3.9,46.3k Reviews,1.5L Salaries,8 Jobs,Banking | Mumbai +1446 other locations
9,Tech Mahindra,3.4,43.7k Reviews,2.9L Salaries,614 Jobs,IT Services & Consulting | Hyderabad +323 othe...
10,Genpact,3.6,42.8k Reviews,2.4L Salaries,586 Jobs,Analytics & KPO | Hyderabad +181 other locations
11,TP,3.9,39k Reviews,99.7k Salaries,1.5k Jobs,BPO | Mumbai +256 other locations
12,Jio,4.4,33.8k Reviews,62k Salaries,-- Jobs,Telecom | Mumbai +1961 other locations
13,Axis Bank,3.6,33.6k Reviews,1L Salaries,242 Jobs,Banking | Mumbai +1524 other locations
14,Concentrix Corporation,3.6,32.6k Reviews,1.3L Salaries,16 Jobs,BPO | Bengaluru +184 other locations
15,Amazon,3.9,31.7k Reviews,1.6L Salaries,74 Jobs,Internet | Bengaluru +518 other locations
16,Reliance Retail,3.9,27.5k Reviews,74.2k Salaries,97 Jobs,Retail | Mumbai +1165 other locations
17,iEnergizer,4.6,27.3k Reviews,24.9k Salaries,97 Jobs,BPO | Noida +53 other locations
18,LTIMindtree,3.6,26.7k Reviews,2L Salaries,543 Jobs,IT Services & Consulting | Bengaluru +145 othe...
19,IBM,3.9,26k Reviews,2.2L Salaries,1.7k Jobs,IT Services & Consulting | Bengaluru +162 othe...

In [115]:
df = pd.DataFrame()

for j in range(1,500):
    
    headers= {'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    webpage = requests.get(f"https://www.ambitionbox.com/list-of-companies?page={j}",headers=headers).text
    
    soup = BeautifulSoup(webpage, 'lxml')
    
    name = []
    rating = []
    review = []
    salary = []
    Jobs = []
    About = []

    for i in company:
        name.append(i.find('h2').text.strip())
        rating.append(i.find('div',class_='rating_text').text.strip())
        review.append(i.find_all('a',class_='companyCardWrapper__ActionWrapper')[0].text.strip())
        salary.append(i.find_all('a',class_='companyCardWrapper__ActionWrapper')[1].text.strip())
        Jobs.append(i.find_all('a',class_='companyCardWrapper__ActionWrapper')[3].text.strip())
        About.append(i.find('span',class_='companyCardWrapper__interLinking').text.strip())
    
    d = {'Name':name, 'Rating':rating, 'Review':review, 'Salary':salary, 'Jobs':Jobs, 'About':About}

    data = pd.DataFrame(d)
    
    df = pd.concat([df,data],ignore_index=True)

In [116]:
df

,Name,Rating,Review,Salary,Jobs,About
0,TCS,3.3,1.2L Reviews,10.2L Salaries,4.3k Jobs,IT Services & Consulting | Bengaluru +445 othe...
1,Accenture,3.7,74.2k Reviews,7.1L Salaries,34.9k Jobs,IT Services & Consulting | Bengaluru +259 othe...
2,Wipro,3.6,65.6k Reviews,4.9L Salaries,319 Jobs,IT Services & Consulting | Hyderabad +374 othe...
3,Cognizant,3.7,62k Reviews,6.1L Salaries,694 Jobs,IT Services & Consulting | Hyderabad +233 othe...
4,Capgemini,3.6,54k Reviews,4.9L Salaries,2.2k Jobs,IT Services & Consulting | Bengaluru +183 othe...
...,...,...,...,...,...,...
9975,Amazon,3.9,31.7k Reviews,1.6L Salaries,74 Jobs,Internet | Bengaluru +518 other locations
9976,Reliance Retail,3.9,27.5k Reviews,74.2k Salaries,97 Jobs,Retail | Mumbai +1165 other locations
9977,iEnergizer,4.6,27.3k Reviews,24.9k Salaries,97 Jobs,BPO | Noida +53 other locations
9978,LTIMindtree,3.6,26.7k Reviews,2L Salaries,543 Jobs,IT Services & Consulting | Bengaluru +145 othe...
9979,IBM,3.9,26k Reviews,2.2L Salaries,1.7k Jobs,IT Services & Consulting | Bengaluru +162 othe...

In [118]:
df.to_excel(r'D:\Machine Learning\Web Scraping\Companies Data.xlsx',index=False)